from mazeworld.envs.pycolab_env import PyColabEnv
from mazeworld.envs.mazeworld_env import MazeWorld
from mazeworld.envs.mazeworld_env import DeepmindMazeWorld_maze
from mazeworld.envs.mazeworld_env import DeepmindMazeWorld_5room